spring.application.name=notification

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notification}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:notification}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:notification}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
